version: "3.8"

services:
  web:
    image: golang:1.23.1
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      GIN_MODE: release
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "
        go mod tidy &&
        ls -la &&
        go run main.go"
    restart: always
    networks:
      - app_network

  db:
    image: mysql:8.0.40
    container_name: db
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: securepassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: mydb
      MYSQL_PASSWORD: securepassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    restart: always
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network: